[toolchain]

[features]
resolution = true
skip-lint = false

[programs.localnet]
vault="8nAcwyJcwSPKndVEbrgA2t8JdP7EPNaBN8yDy5m4QCzH"
[programs.devnet]
vault="8nAcwyJcwSPKndVEbrgA2t8JdP7EPNaBN8yDy5m4QCzH"
[programs.mainnet]
vault="8nAcwyJcwSPKndVEbrgA2t8JdP7EPNaBN8yDy5m4QCzH"


[registry]
url = "https://solana-mainnet.g.alchemy.com/v2/TrqwOCcz41D4_TJFUT41sc08JFX9AqJA"

[provider]
cluster = "devnet"
wallet = "~/.config/solana/id.json"

[scripts]
test = "yarn ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
mintToken ="yarn ts-node migrations/transferMusd.ts"

